### PR TITLE
feat: support the discussion for episode

### PR DESCRIPTION
**Pull request by LinuxSuRen**

### CODE REVIEW

**Review by sxzz — COMMENTED** [review]
Seems to `@giscus/vue` is not supported SSR/SSG.

**Comment by LinuxSuRen** [comment]
I'm not able to see the deploy log output. If only we have a team account to see it?

**Comment by sxzz** [comment]
@LinuxSuRen I'll try to fix it later.

**Comment by sxzz** [comment]
Wait issue https://github.com/giscus/giscus-component/pull/573

**Comment by LinuxSuRen** [comment]
hi @sxzz , the upstream PR was merged. What should we do next?

**Review by sxzz — APPROVED** [review]

**Pull request merged**
