### PR TITLE
feat: add sponsor link

### PR DESCRIPTION
**Pull request by LinuxSuRen**

### CODE REVIEW

**Comment by sxzz** [comment]
Please run `pnpm run lint --fix` to format files.

**Comment by LinuxSuRen** [comment]
I got some errors when running the lint command. Please feel free to help me resolve it.

```shell
> opensource-f2f-website@0.0.0 lint /home/suren/ws/opensource-f2f/website
> eslint --ext .js,.ts,.vue .


Oops! Something went wrong! :(

ESLint: 8.23.0

/home/suren/ws/opensource-f2f/website/node_modules/.pnpm/yaml@2.1.1/node_modules/yaml/dist/compose/composer.js:33
                if (prelude[i + 1]?.[0] !== '#')
                                   ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/suren/ws/opensource-f2f/website/node_modules/.pnpm/yaml@2.1.1/node_modules/yaml/dist/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
 ELIFECYCLE  Command failed with exit code 2
```

**Comment by sxzz** [comment]
Your nodejs version is too low, please try > `16`

**Review by sxzz — APPROVED** [review]

**Comment by LinuxSuRen** [comment]
> Your nodejs version is too low, please try > `16` (I've fixed format issue for this PR)

Great. It works well after I upgraded the node to `16`.

In order to make it to be clear for someone who is not familiar with the front-end tech. I made this https://github.com/opensource-f2f/website/pull/17

**Pull request merged**
